import type { ProviderCatalogEntry } from "./types.js";
import { modelsForProvider } from "./models.js";
import { catalogAliases, mergeProviderEntries } from "./dedupe.js";

/**
 * The COKEY provider catalog.
 *
 * Design rules, enforced by review rather than by types:
 *
 * 1. A user never types a provider name, base URL or auth scheme. They pick a
 *    card from this list.
 * 2. `freeTier.advertised` is only `true` when the provider itself advertises a
 *    free tier. Trial credits do not count.
 * 3. `knownModels` lists only models reachable on the free tier. If a model is
 *    not free it does not appear in the Add-Chain picker.
 * 4. Model lists are a curated seed. For providers verified via `method:
 *    "models"`, COKEY reconciles the seed against the provider's live list when
 *    a credential is connected or tested.
 *
 * Adding a provider is a data change: append an entry here. No router, adapter
 * or UI code needs to change for another OpenAI-compatible service.
 */
export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "aion",
    displayName: "AION Labs",
    baseUrl: "https://api.aionlabs.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://aionlabs.ai/",
    freeTier: { advertised: true, summary: "15 RPM · 20,000 TPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b", "llama-3.3-70b-instruct"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "agnes",
    displayName: "Agnes AI",
    baseUrl: "https://apihub.agnes-ai.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://agnes-ai.com/",
    freeTier: { advertised: true, summary: "20 RPM · 1,000 RPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "llama-3.3-70b-instruct"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "anyapi",
    displayName: "AnyAPI AI",
    baseUrl: "https://api.anyapi.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://anyapi.ai/",
    freeTier: { advertised: true, summary: "100,000 TPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "auriko",
    displayName: "Auriko",
    baseUrl: "https://api.auriko.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://auriko.ai/",
    freeTier: { advertised: true, summary: "500 RPM · BYOK", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "llama-3.3-70b-instruct", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes: "Rate limit is generous but the key is your own upstream key (BYOK).",
  },
  {
    id: "bazaarlink",
    displayName: "BazaarLink",
    baseUrl: "https://api.bazaarlink.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://bazaarlink.ai/",
    freeTier: { advertised: true, summary: "10 RPM · 50 RPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "cerebras",
    displayName: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://cloud.cerebras.ai/",
    freeTier: { advertised: true, summary: "Free tier with rate limits", quotaSource: "provider" },
    knownModels: ["llama-3.3-70b", "llama-4-scout-17b-16e-instruct", "qwen-3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "cloudflare",
    displayName: "Cloudflare Workers AI",
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
    apiStyle: "cloudflare",
    authScheme: "bearer",
    signupUrl: "https://dash.cloudflare.com/profile/api-tokens",
    docsUrl: "https://developers.cloudflare.com/workers-ai/",
    freeTier: {
      advertised: true,
      summary: "10,000 RPD shared across all models",
      quotaSource: "provider",
    },
    knownModels: [
      "@cf/qwen/qwen3.8-27b",
      "@cf/qwen/qwen3-30b-a3b-fp8",
      "@cf/qwen/qwen2.5-coder-32b-instruct",
      "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
      "@cf/meta/llama-4-scout-17b-16e-instruct",
      "@cf/openai/gpt-oss-120b",
      "@cf/openai/gpt-oss-20b",
      "@cf/mistralai/mistral-small-3.1-24b-instruct",
      "@cf/google/gemma-4-26b-a4b-it",
      "@cf/zai-org/glm-4.7-flash",
    ],
    credentialFields: ["secret", "accountId"],
    verification: { method: "chat", model: "@cf/qwen/qwen3-30b-a3b-fp8" },
    notes: "Requires both an API token and the Cloudflare account id.",
  },
  {
    id: "cohere",
    displayName: "Cohere AI",
    baseUrl: "https://api.cohere.com/v2",
    apiStyle: "cohere",
    authScheme: "bearer",
    signupUrl: "https://dashboard.cohere.com/api-keys",
    freeTier: { advertised: true, summary: "20 RPM · 1,000 calls/month", quotaSource: "provider" },
    knownModels: [
      "command-a-03-2025",
      "command-r-08-2024",
      "command-r-plus-08-2024",
      "command-r7b-12-2024",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "electronhub",
    displayName: "ElectronHub",
    baseUrl: "https://api.electronhub.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://electronhub.ai/",
    freeTier: { advertised: true, summary: "5 RPM", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "evolvex",
    displayName: "EvolveX",
    baseUrl: "https://api.evolvex.gg/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://evolvex.gg/",
    freeTier: { advertised: true, summary: "5 RPM · unspecified RPD", quotaSource: "unknown" },
    knownModels: [
      "google/diffusiongemma-26b-a4b-it",
      "meta/llama-3.2-11b-vision-instruct",
      "minimaxai/minimax-m3",
      "moonshotai/kimi-k3",
      "nvidia/nemotron-3-super-120b-a12b",
      "openai/gpt-oss-20b",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "fastrouter",
    displayName: "FastRouter",
    baseUrl: "https://api.fastrouter.ai/api/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://fastrouter.ai/",
    freeTier: { advertised: true, summary: "10 RPD per model", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "freeai",
    displayName: "Free.ai",
    baseUrl: "https://api.free.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://free.ai/",
    freeTier: { advertised: true, summary: "10 RPM · 30,000 TPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "llama-3.3-70b-instruct"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "freeinference",
    displayName: "FreeInference",
    baseUrl: "https://freeinference.org/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://freeinference.org/",
    freeTier: { advertised: true, summary: "$20 of credits per day", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "qwen3-32b", "llama-3.3-70b-instruct"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "gemini",
    displayName: "Google Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiStyle: "google",
    authScheme: "query-param",
    signupUrl: "https://aistudio.google.com/app/apikey",
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    freeTier: {
      advertised: true,
      summary: "5–20 RPM · 20–500 RPD · varies per model",
      quotaSource: "provider",
    },
    knownModels: [
      "models/gemini-2.5-flash",
      "models/gemini-2.5-flash-lite",
      "models/gemini-3-flash-preview",
      "models/gemini-3.1-flash-lite",
      "models/gemini-3.5-flash",
      "models/gemini-flash-latest",
      "models/gemma-4-26b-a4b-it",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "gonka",
    displayName: "Gonka Broker",
    baseUrl: "https://proxy.gonkabroker.com/v1/",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://gonkabroker.com/",
    freeTier: { advertised: true, summary: "6 RPM", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "groq",
    displayName: "Groq API",
    baseUrl: "https://api.groq.com/openai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://console.groq.com/keys",
    docsUrl: "https://console.groq.com/docs",
    freeTier: {
      advertised: true,
      summary: "30 RPM · 14,400 RPD · 18,000 TPM",
      quotaSource: "provider",
    },
    knownModels: [
      "qwen/qwen3.8-27b",
      "qwen/qwen3.6-27b",
      "openai/gpt-oss-120b",
      "openai/gpt-oss-20b",
      "groq/compound",
      "groq/compound-mini",
      "allam-2-7b",
    ],
    credentialFields: ["secret"],
    verification: { method: "chat", model: "qwen/qwen3.8-27b" },
  },
  {
    id: "helixmind",
    displayName: "HelixMind",
    baseUrl: "https://helixmind.online/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://helixmind.online/",
    freeTier: { advertised: true, summary: "3 RPM · 50 RPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "huggingface",
    displayName: "Hugging Face",
    baseUrl: "https://router.huggingface.co/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://huggingface.co/settings/tokens",
    docsUrl: "https://huggingface.co/docs/inference-providers",
    freeTier: {
      advertised: true,
      summary: "$0.10 of monthly inference credits",
      quotaSource: "provider",
    },
    knownModels: [
      "openai/gpt-oss-120b",
      "openai/gpt-oss-20b",
      "meta-llama/Llama-3.3-70B-Instruct",
      "Qwen/Qwen3-32B",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "internai",
    displayName: "Intern AI",
    baseUrl: "https://chat.intern-ai.org.cn/api/v1/",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://chat.intern-ai.org.cn/",
    freeTier: { advertised: true, summary: "90M tokens/month", quotaSource: "provider" },
    knownModels: ["internlm3-8b-instruct", "internlm2.5-20b-chat"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "kilo",
    displayName: "Kilo Gateway",
    baseUrl: "https://api.kilo.ai/api/gateway",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://app.kilo.ai/",
    freeTier: { advertised: true, summary: "5 RPM · 200 RPD", quotaSource: "provider" },
    knownModels: [
      "cohere/north-mini-code:free",
      "nvidia/nemotron-3-super-120b-a12b:free",
      "poolside/laguna-xs-2.1:free",
      "stepfun/step-3.7-flash:free",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "llmkiwi",
    displayName: "LLM.Kiwi",
    baseUrl: "https://api.llm.kiwi/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://llm.kiwi/",
    freeTier: { advertised: true, summary: "40 RPH", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "llm7",
    displayName: "LLM7.IO",
    baseUrl: "https://api.llm7.io/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://llm7.io/",
    freeTier: { advertised: true, summary: "40 RPM", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b", "llama-3.3-70b-instruct"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "literouter",
    displayName: "LiteRouter",
    baseUrl: "https://api.literouter.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://literouter.com/",
    freeTier: {
      advertised: true,
      summary: "Uncapped requests for :free models",
      quotaSource: "unknown",
    },
    knownModels: [
      "deepseek-v4-flash:free",
      "glm-4.7:free",
      "gpt-oss-120b:free",
      "qwen3.8-27b:free",
      "gemma-4-26b-a4b-it:free",
      "kimi-k2.7-code:free",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "meganova",
    displayName: "MegaNova AI",
    baseUrl: "https://api.meganova.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://meganova.ai/",
    freeTier: { advertised: true, summary: "60 RPM · 550 RPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "mistral",
    displayName: "Mistral AI",
    baseUrl: "https://api.mistral.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://console.mistral.ai/api-keys/",
    docsUrl: "https://docs.mistral.ai/",
    freeTier: {
      advertised: true,
      summary: "~2–30 RPM · 50,000 TPM shared pool",
      quotaSource: "provider",
    },
    knownModels: [
      "codestral-latest",
      "codestral-2508",
      "ministral-14b-latest",
      "ministral-8b-latest",
      "ministral-3b-latest",
      "mistral-code-latest",
    ],
    credentialFields: ["secret"],
    verification: { method: "chat", model: "ministral-3b-latest" },
  },
  {
    id: "mixlayer",
    displayName: "Mixlayer",
    baseUrl: "https://models.mixlayer.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://mixlayer.ai/",
    freeTier: { advertised: true, summary: "20 RPM", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "llama-3.3-70b-instruct", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "naga",
    displayName: "Naga AI",
    baseUrl: "https://api.naga.ac/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://naga.ac/",
    freeTier: { advertised: true, summary: "10 RPM · 100 RPD", quotaSource: "provider" },
    knownModels: [
      "dots-3-note-preview:free",
      "ling-3.0-flash-fin:free",
      "nemotron-3-super-120b-a12b:free",
      "nemotron-3.5-lightning:free",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "nvidia",
    displayName: "NVIDIA NIM",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://build.nvidia.com/",
    docsUrl: "https://docs.api.nvidia.com/",
    freeTier: {
      advertised: true,
      summary: "40 RPM · recurring free budget, eval-only ToS",
      quotaSource: "provider",
    },
    knownModels: [
      "deepseek-ai/deepseek-v4-flash-0731",
      "deepseek-ai/deepseek-v4-pro-0813",
      "meta/llama-3.2-11b-vision-instruct",
      "meta/muse-glimmer-30b",
      "moonshotai/kimi-k3",
      "nvidia/nemotron-3-super-120b-a12b",
      "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
      "openai/gpt-oss-20b",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "NVIDIA NIM replaced depleting trial credits with a recurring per-account rate limit (40 RPM default, varies by model). The free tier's ToS scopes usage to evaluation/prototyping, not production.",
  },
  {
    id: "odirouter",
    displayName: "Odirouter",
    baseUrl: "https://api.odirouter.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://odirouter.ai/",
    freeTier: { advertised: true, summary: "5 RPM · 50 RPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "ollama",
    displayName: "Ollama Cloud",
    baseUrl: "https://api.ollama.com",
    apiStyle: "ollama",
    authScheme: "bearer",
    signupUrl: "https://ollama.com/",
    docsUrl: "https://docs.ollama.com/cloud",
    freeTier: {
      advertised: true,
      summary: "5-hour session · weekly reset",
      quotaSource: "unknown",
    },
    knownModels: [
      "gemma4:31b",
      "gpt-oss:120b",
      "gpt-oss:20b",
      "nemotron-3-nano:30b",
      "nemotron-3-super",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "opencode-zen",
    displayName: "OpenCode Zen",
    baseUrl: "https://opencode.ai/zen/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://opencode.ai/zen",
    docsUrl: "https://opencode.ai/docs/zen",
    freeTier: { advertised: true, summary: "30 RPM · 500 RPD · 1M TPD", quotaSource: "provider" },
    extraHeaders: { "x-opencode-session": "cokey" },
    knownModels: [
      "big-pickle",
      "laguna-s-2.1-free",
      "ling-3.0-flash-fin-free",
      "mimo-v2.5-free",
      "nemotron-3-ultra-free",
      "nemotron-3.5-lightning-free",
    ],
    credentialFields: ["secret"],
    verification: { method: "chat", model: "big-pickle" },
  },
  {
    id: "openrouter",
    displayName: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://openrouter.ai/keys",
    docsUrl: "https://openrouter.ai/docs",
    freeTier: { advertised: true, summary: "20 RPM · 50 RPD", quotaSource: "provider" },
    knownModels: [
      "cohere/north-mini-code:free",
      "dots-studio/dots-3-note-preview:free",
      "google/gemma-4-26b-a4b-it:free",
      "inclusionai/ling-3.0-flash-fin:free",
      "nvidia/nemotron-3-super-120b-a12b:free",
      "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
      "poolside/laguna-s-2.1:free",
      "poolside/laguna-xs-2.1:free",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "orcarouter",
    displayName: "Orcarouter",
    baseUrl: "https://api.orcarouter.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://orcarouter.ai/",
    freeTier: {
      advertised: true,
      summary: "Free tier, limits unspecified",
      quotaSource: "unknown",
    },
    knownModels: ["gpt-oss-120b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "poixe",
    displayName: "Poixe AI",
    baseUrl: "https://api.poixe.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://poixe.com/",
    freeTier: { advertised: true, summary: "10,000 RPD · 10M TPD", quotaSource: "unknown" },
    knownModels: [
      "gpt-4o-mini:free",
      "gpt-4.1-mini:free",
      "gemini-2.5-flash:free",
      "deepseek-chat:free",
      "qwen-plus:free",
      "gpt-oss-120b:free",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "pooled",
    displayName: "Pooled AI",
    baseUrl: "https://ai.pooled.dev/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://pooled.dev/",
    freeTier: { advertised: true, summary: "1M TPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "poolside",
    displayName: "Poolside",
    baseUrl: "https://inference.poolside.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://poolside.ai/",
    freeTier: { advertised: true, summary: "20 RPM · 200 RPD · 1M TPD", quotaSource: "provider" },
    knownModels: ["poolside/laguna-s-2.1", "poolside/laguna-xs-2.1"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "requesty",
    displayName: "Requesty",
    baseUrl: "https://router.requesty.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://requesty.ai/",
    freeTier: { advertised: true, summary: "200 RPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "qwen3-32b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "routeway",
    displayName: "Routeway AI",
    baseUrl: "https://api.routeway.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://routeway.ai/",
    freeTier: { advertised: true, summary: "5 RPM", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b", "llama-3.3-70b-instruct"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "sealion",
    displayName: "SEA-LION",
    baseUrl: "https://api.sea-lion.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://sea-lion.ai/",
    freeTier: { advertised: true, summary: "10 RPM", quotaSource: "provider" },
    knownModels: ["sealion-v3-32b", "sealion-v3-8b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "tokenreply",
    displayName: "TokenReply",
    baseUrl: "https://api.tokenreply.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://tokenreply.com/",
    freeTier: { advertised: true, summary: "3 RPM", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "voidai",
    displayName: "Void AI",
    baseUrl: "https://api.voidai.app/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://voidai.app/",
    freeTier: {
      advertised: true,
      summary: "100 RPM · 125,000 daily credits",
      quotaSource: "unknown",
    },
    knownModels: [
      "gpt-4o-mini",
      "gpt-4.1-mini",
      "gemini-2.5-flash",
      "deepseek-v4-flash",
      "kimi-k2.6",
      "qwen3-235b-a22b-instruct",
      "qwen3.8-27b:free",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "xkiro",
    displayName: "xKiro AI",
    baseUrl: "https://api.xkiro.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://xkiro.com/",
    freeTier: {
      advertised: true,
      summary: "5M TPD · free models only",
      quotaSource: "unknown",
      freeModelsOnly: true,
    },
    knownModels: [
      "qwen/qwen3.8-max:free",
      "qwen/qwen3.6-27b:free",
      "minimax/minimax-m3:free",
      "mistralai/codestral-2508",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "yolo",
    displayName: "Yolo-Auto",
    baseUrl: "https://yolo-auto.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://yolo-auto.com/",
    freeTier: { advertised: true, summary: "15 RPD", quotaSource: "provider" },
    knownModels: ["gpt-oss-120b", "gpt-oss-20b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "zai",
    displayName: "Z.AI (Zhipu AI)",
    baseUrl: "https://api.z.ai/api/paas/v4",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://z.ai/",
    freeTier: { advertised: true, summary: "Uncapped TPD · 1 concurrent", quotaSource: "unknown" },
    knownModels: ["glm-4.7-flash", "glm-4.5-flash"],
    credentialFields: ["secret"],
    verification: { method: "chat", model: "glm-4.5-flash" },
  },
  {
    id: "zydit",
    displayName: "Zydit AI",
    baseUrl: "https://api.zydit.in/v3",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://zydit.in/",
    freeTier: { advertised: true, summary: "Unlimited requests · 10 RPM", quotaSource: "unknown" },
    knownModels: [
      "big-pickle",
      "deepseek-r1:latest",
      "gemma-4-31b",
      "mimo-v2.5",
      "nemotron-3-ultra-max",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "zylo",
    displayName: "Zylo API",
    baseUrl: "https://api.zyloai.net/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://zyloai.net/",
    freeTier: {
      advertised: true,
      summary: "10 RPM · 7,200 RPD · 200,000 TPD",
      quotaSource: "provider",
    },
    knownModels: ["gpt-oss-20b", "minimax-m3", "nemotron-3-ultra", "zylo-flash", "zylo-pro"],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "qzz",
    displayName: "QZZ API",
    baseUrl: "https://0api.qzz.io/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://qzz.io/",
    freeTier: {
      advertised: true,
      summary: "Free DeepSeek models · ~1 request per 5 minutes",
      quotaSource: "unknown",
    },
    knownModels: [
      "deepseek-v4-flash",
      "deepseek-v4-flash-0731",
      "deepseek-v4-pro",
      "deepseek-v4-pro-0813",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "Rate-limited to roughly one request every 5 minutes per key (measured, not published). Fine for one-off tests, too slow for real chains.",
  },
  {
    id: "ai121628",
    displayName: "AI 121628 Free",
    baseUrl: "https://ai.121628.xyz/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://ai.121628.xyz/",
    freeTier: {
      advertised: true,
      summary: "Free models · no published rate limit",
      quotaSource: "unknown",
    },
    knownModels: ["deepseek-v4-flash-free"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "deepseek-v4-flash-free responds without an observed per-request cap. deepseek-v4-pro-free consistently resets the connection and is intentionally not listed.",
  },
  {
    id: "tokenrouter",
    displayName: "TokenRouter",
    baseUrl: "https://api.tokenrouter.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://tokenrouter.com/",
    freeTier: {
      advertised: true,
      summary: "Free tier · limited capacity, stability not guaranteed",
      quotaSource: "provider",
    },
    knownModels: ["z-ai/glm-5.3-free"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "Free models run on shared compute: capacity is limited and service stability/concurrency are not guaranteed.",
  },
  {
    id: "tokenharbor",
    displayName: "TokenHarbor",
    baseUrl: "https://tokenharbor.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://tokenharbor.ai/dashboard",
    freeTier: {
      advertised: true,
      summary: "Free models · limits unspecified",
      quotaSource: "unknown",
    },
    knownModels: ["deepseek-v4.1-flash:free", "deepseek-v4-flash:free", "mimo-v2.5:free"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "Requires email verification before requests start working. On free tier the same caveat applies: shared, capacity-limited compute.",
  },
  {
    id: "nararouter",
    displayName: "NaraRouter",
    baseUrl: "https://router.bynara.id/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://bynara.id/settings",
    freeTier: {
      advertised: true,
      summary: "Free laguna-s-2.1 · DeepSeek models paid",
      quotaSource: "unknown",
    },
    knownModels: ["laguna-s-2.1"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "Requires a Telegram account bound and a required group joined before the API unlocks. laguna-s-2.1 is free and verified; deepseek-v4-flash and deepseek-v4-pro need paid credits.",
  },
  {
    id: "aihubmix",
    displayName: "AIHubMix",
    baseUrl: "https://aihubmix.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://aihubmix.com/",
    freeTier: {
      advertised: true,
      summary: "Selected free models · others intermittently unavailable",
      quotaSource: "unknown",
    },
    knownModels: ["coding-minimax-m3-free", "gpt-5.5-free", "coding-glm-4.7-free"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "Only these three :free models verified working. minimax-m2.7-free, gpt-oss-20b-free, kimi-for-coding-free, and mimo-v2-flash-free were no_available_channel at test time, and laguna-s-2.1-free returned an HTTP 429 — model availability on the free tier is intermittent.",
  },
  {
    id: "fhrouter",
    displayName: "FH Router",
    baseUrl: "https://fhrouter.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://fhrouter.com/",
    freeTier: { advertised: true, summary: "Free 'on the house' models", quotaSource: "unknown" },
    knownModels: ["deepseek-v4-flash", "grok-4.6"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "deepseek-v4-flash and grok-4.6 verified free. glm-5.3-flash is advertised free but had no serving channel (get_channel_failed) at test time.",
  },
  {
    id: "amdradeon",
    displayName: "AMD Radeon API",
    baseUrl: "https://developer.amd.com.cn/radeon/api/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://developer.amd.com.cn/",
    docsUrl: "https://developer.amd.com.cn/radeon/",
    freeTier: {
      advertised: false,
      summary: "Paid model · works with a funded key",
      quotaSource: "unknown",
    },
    knownModels: ["DeepSeek-V4-Flash"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "Marked paid (per-token pricing, model metadata free:false) but verified serving fine with a funded key. Stability is experimental.",
  },
  {
    id: "wusrouter",
    displayName: "WusRouter",
    baseUrl: "https://api.wusrouter.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://wusrouter.com/",
    freeTier: { advertised: true, summary: "Selected free models", quotaSource: "unknown" },
    knownModels: ["DeepSeek-R1-0528-Qwen3-8B", "qwen3.8-27b"],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "DeepSeek-R1-0528-Qwen3-8B and qwen3.8-27b verified. deepseek/deepseek-chat-v3.1 is advertised in /models but returns model_not_found (no available channel) and is intentionally not listed.",
  },
  {
    id: "pollinations",
    displayName: "Pollinations",
    baseUrl: "https://gen.pollinations.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://pollinations.ai/",
    docsUrl: "https://docs.pollinations.ai/",
    freeTier: { advertised: true, summary: "Free community-hosted models", quotaSource: "unknown" },
    knownModels: [
      "community/Catniti/deepseek-r1-free",
      "community/AkshayCoder48/poolside-laguna-s-2.1:free",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      '"community/" models are open endpoints hosted by other users, free but availability depends on the host. These two verified: deepseek-r1-free (routed to tb/deepseek-r1) and poolside-laguna-s-2.1:free (routed to kc/poolside/laguna-s-2.1:free).',
  },
  {
    id: "modelscope",
    displayName: "ModelScope",
    baseUrl: "https://api-inference.modelscope.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://modelscope.ai/",
    docsUrl: "https://www.modelscope.cn/docs",
    freeTier: {
      advertised: false,
      summary: "Paid models · works with a funded key",
      quotaSource: "unknown",
    },
    knownModels: [
      "deepseek-ai/DeepSeek-V3.1",
      "deepseek-ai/DeepSeek-V3.2-Exp",
      "deepseek-ai/DeepSeek-V4-Pro",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
    ],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes:
      "Alibaba's official inference API with canonical DeepSeek model names. All four DeepSeek models verified. Requires an Alibaba Cloud account bound to the ModelScope token before requests work. Paid per-token.",
  },

  // -------------------------------------------------------------------------
  // Further free hubs.
  //
  // Same rules as above: the provider itself advertises a self-replenishing
  // free tier, no credit card is required, and the endpoint is a standard
  // OpenAI-compatible call.
  // -------------------------------------------------------------------------
  {
    id: "aion-labs",
    displayName: "AION Labs",
    baseUrl: "https://api.aionlabs.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://www.aionlabs.ai",
    freeTier: { advertised: true, summary: "15 RPM · 20,000 TPD", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "agnes-ai",
    displayName: "Agnes AI",
    baseUrl: "https://apihub.agnes-ai.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://www.agnes-ai.com",
    freeTier: { advertised: true, summary: "20 RPM · 1,000 RPD", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "anyapi",
    displayName: "AnyAPI AI",
    baseUrl: "https://api.anyapi.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://anyapi.ai",
    freeTier: { advertised: true, summary: "100,000 tokens/day", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "auriko",
    displayName: "Auriko",
    baseUrl: "https://api.auriko.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://www.auriko.ai",
    freeTier: {
      advertised: true,
      summary: "500 RPM (BYOK) · permanently-free models",
      quotaSource: "provider",
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "bazaarlink",
    displayName: "BazaarLink",
    baseUrl: "https://api.bazaarlink.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://bazaarlink.ai",
    freeTier: { advertised: true, summary: "10 RPM · 50 RPD", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "electronhub",
    displayName: "ElectronHub",
    baseUrl: "https://api.electronhub.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://electronhub.ai",
    freeTier: {
      advertised: true,
      summary: "5 RPM · $0.25 weekly credits",
      quotaSource: "provider",
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes: "Weekly credit cap; not suitable as a chain's first entry.",
  },
  {
    id: "fastrouter",
    displayName: "FastRouter",
    baseUrl: "https://api.fastrouter.ai/api/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://fastrouter.ai",
    freeTier: { advertised: true, summary: "10 RPD per model", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "freeai",
    displayName: "Free.ai",
    baseUrl: "https://api.free.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://free.ai",
    freeTier: { advertised: true, summary: "10 RPM · 30,000 TPD", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "freeinference",
    displayName: "FreeInference",
    baseUrl: "https://freeinference.org/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://freeinference.org",
    freeTier: {
      advertised: true,
      summary: "$20 daily credits · 2 concurrent",
      quotaSource: "provider",
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes: "New accounts may go through manual review.",
  },
  {
    id: "gonka-broker",
    displayName: "Gonka Broker",
    baseUrl: "https://proxy.gonkabroker.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://gonkabroker.com/",
    freeTier: {
      advertised: true,
      summary: "6 RPM · ~1M tokens per month",
      quotaSource: "provider",
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes: "Requires phone verification before free monthly tokens unlock.",
  },
  {
    id: "helixmind",
    displayName: "HelixMind",
    baseUrl: "https://helixmind.online/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://helixmind.online",
    freeTier: { advertised: true, summary: "3 RPM · 50 RPD", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "huggingface",
    displayName: "Hugging Face",
    baseUrl: "https://router.huggingface.co/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://huggingface.co/settings/tokens",
    freeTier: { advertised: true, summary: "$0.10/month credits", quotaSource: "unknown" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "intern-ai",
    displayName: "Intern AI",
    baseUrl: "https://chat.intern-ai.org.cn/api/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://internlm.intern-ai.org.cn",
    freeTier: {
      advertised: true,
      summary: "30 RPM · 300,000 TPM · 90M tokens/month",
      quotaSource: "provider",
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "llm-kiwi",
    displayName: "LLM.Kiwi",
    baseUrl: "https://api.llm.kiwi/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://llm.kiwi",
    freeTier: { advertised: true, summary: "40 requests/hour", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "llm7",
    displayName: "LLM7.IO",
    baseUrl: "https://api.llm7.io/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://llm7.io",
    freeTier: { advertised: true, summary: "40 RPM · 2,400 RPD · 1M TPD", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "meganova",
    displayName: "MegaNova AI",
    baseUrl: "https://api.meganova.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://meganova.ai",
    freeTier: {
      advertised: true,
      summary: "60 RPM · 550 RPD · 200,000 TPM",
      quotaSource: "provider",
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "mixlayer",
    displayName: "Mixlayer",
    baseUrl: "https://models.mixlayer.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://www.mixlayer.com",
    freeTier: { advertised: true, summary: "20 RPM", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "odirouter",
    displayName: "Odirouter",
    baseUrl: "https://api.odirouter.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://odirouter.ai",
    freeTier: {
      advertised: true,
      summary: "5 RPM · 50 RPD · free models only",
      quotaSource: "provider",
      freeModelsOnly: true,
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
    notes: "Hosted in Russia; some free models are region-sensitive.",
  },
  {
    id: "orcarouter",
    displayName: "Orcarouter",
    baseUrl: "https://api.orcarouter.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://orcarouter.ai",
    freeTier: { advertised: true, summary: "Free models only", quotaSource: "unknown" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "pooled-ai",
    displayName: "Pooled AI",
    baseUrl: "https://ai.pooled.dev/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://ai.pooled.dev",
    freeTier: { advertised: true, summary: "1M TPD · MiniMax models", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "requesty",
    displayName: "Requesty",
    baseUrl: "https://router.requesty.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://requesty.ai",
    freeTier: {
      advertised: true,
      summary: "200 RPD · free models only",
      quotaSource: "provider",
      freeModelsOnly: true,
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "routeway",
    displayName: "Routeway AI",
    baseUrl: "https://api.routeway.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://routeway.ai",
    freeTier: {
      advertised: true,
      summary: "5 RPM · 200 RPD · 300,000 TPD",
      quotaSource: "provider",
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "sea-lion",
    displayName: "SEA-LION",
    baseUrl: "https://api.sea-lion.ai/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://playground.sea-lion.ai",
    freeTier: { advertised: true, summary: "10 RPM", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "tokenreply",
    displayName: "TokenReply",
    baseUrl: "https://api.tokenreply.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://tokenreply.com",
    freeTier: {
      advertised: true,
      summary: "3 RPM · free models only",
      quotaSource: "provider",
      freeModelsOnly: true,
    },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
  {
    id: "yolo-auto",
    displayName: "Yolo-Auto",
    baseUrl: "https://yolo-auto.com/v1",
    apiStyle: "openai",
    authScheme: "bearer",
    signupUrl: "https://yolo-auto.com",
    freeTier: { advertised: true, summary: "15 RPD", quotaSource: "provider" },
    knownModels: [],
    credentialFields: ["secret"],
    verification: { method: "models" },
  },
];

/**
 * Keep `knownModels` in lockstep with the curated model catalog.
 *
 * One source of truth means the provider list, credential verification and the
 * chain validator can never disagree about which models a provider serves.
 */
for (const provider of PROVIDER_CATALOG) {
  const curated = modelsForProvider(provider.id);
  if (curated.length > 0) provider.knownModels = curated.map((model) => model.id);
}

/**
 * The catalog with duplicates collapsed.
 *
 * Consumers must use this rather than `PROVIDER_CATALOG`: the raw list carries
 * a handful of services listed twice, and reading it directly means a sparse
 * duplicate silently wins over the curated entry it duplicates.
 */
const CANONICAL = mergeProviderEntries(PROVIDER_CATALOG);

/**
 * Raw ids that were collapsed into a surviving entry, for example
 * `aion-labs` into `aion`. Stored chains still reference the old id, so it has
 * to keep resolving.
 */
export const PROVIDER_ALIASES: Map<string, string> = catalogAliases(PROVIDER_CATALOG, CANONICAL);

/** Catalog index for O(1) lookups, including deprecated aliases. */
const BY_ID = new Map(CANONICAL.map((p) => [p.id, p]));
for (const [alias, target] of PROVIDER_ALIASES) {
  const entry = BY_ID.get(target);
  if (entry) BY_ID.set(alias, entry);
}

/** Deduplicated catalog, one entry per real service. */
export function providerCatalog(): ProviderCatalogEntry[] {
  return CANONICAL;
}

export function findProvider(id: string): ProviderCatalogEntry | undefined {
  return BY_ID.get(id);
}

/** Providers that explicitly advertise a free tier. */
export function freeProviders(): ProviderCatalogEntry[] {
  return CANONICAL.filter((p) => p.freeTier.advertised);
}

export function paidProviders(): ProviderCatalogEntry[] {
  return CANONICAL.filter((p) => !p.freeTier.advertised);
}

export function isFreeProvider(id: string): boolean {
  return findProvider(id)?.freeTier.advertised ?? false;
}

/** Case-insensitive search across id, display name and summary. */
export function searchProviders(query: string): ProviderCatalogEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...CANONICAL];
  return CANONICAL.filter((p) =>
    [p.id, p.displayName, p.freeTier.summary, ...p.knownModels].some((field) =>
      field.toLowerCase().includes(q),
    ),
  );
}

export function providerIds(): string[] {
  return CANONICAL.map((p) => p.id);
}
