#!/usr/bin/env node


import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "src", "web", "public", "fonts");
const CSS_OUT = join(ROOT, "src", "web", "styles", "fonts.css");


const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";


const FAMILIES = [
  {
    query: "Work+Sans:wght@400;500;600;700",
    slug: "work-sans",
    display: "Work Sans",
  },
  {
    query: "Instrument+Serif:ital@0;1",
    slug: "instrument-serif",
    display: "Instrument Serif",
  },
];

const MAX_FONT_BYTES = 5 * 1024 * 1024;

async function get(url) {
  const response = await fetch(url, { headers: { "user-agent": UA } });
  if (!response.ok) throw new Error(`${url} answered ${response.status}`);
  return response;
}

async function getFontBytes(url) {
  const response = await get(url);
  const contentLength = response.headers.get("content-length");
  if (contentLength && Number(contentLength) > MAX_FONT_BYTES) {
    throw new Error(`${url} is larger than the ${MAX_FONT_BYTES} byte font size cap`);
  }
  const bytes = Buffer.from(await response.arrayBuffer());
  if (bytes.length > MAX_FONT_BYTES) {
    throw new Error(`${url} is larger than the ${MAX_FONT_BYTES} byte font size cap`);
  }
  return bytes;
}


const FACE_PATTERN =
  /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g;

function parseFaces(css) {
  const faces = [];
  for (const match of css.matchAll(FACE_PATTERN)) {
    const [, subset, body] = match;
    const weight = /font-weight:\s*([^;]+);/.exec(body)?.[1]?.trim();
    const style = /font-style:\s*([^;]+);/.exec(body)?.[1]?.trim() ?? "normal";
    const url = /src:\s*url\(([^)]+)\)/.exec(body)?.[1];
    if (subset !== "latin" || !weight || !url) continue;
    faces.push({ weight, style, url });
  }
  return faces;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const declarations = [];
  let downloaded = 0;
  let reused = 0;

  for (const family of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`;
    const css = await (await get(url)).text();
    const faces = parseFaces(css);

    if (faces.length === 0) {
      console.warn(`! no latin faces for ${family.slug}`);
      continue;
    }

    
    
    
    
    
    
    const byUrl = new Map();
    for (const face of faces) {
      const group = byUrl.get(face.url) ?? [];
      group.push(face);
      byUrl.set(face.url, group);
    }

    for (const [srcUrl, group] of byUrl) {
      const weights = group.map((face) => Number(face.weight)).sort((a, b) => a - b);
      const isVariable = group.length > 1;
      const weightLabel = isVariable
        ? `${weights[0]} ${weights[weights.length - 1]}`
        : group[0].weight;
      const weightSlug = isVariable
        ? "variable"
        : weightLabel.replace(/[^0-9]/g, "-").replace(/-+/g, "-");
      const style = group[0].style;
      const styleSlug = style === "italic" ? "-italic" : "";
      const file = `${family.slug}-${weightSlug}${styleSlug}.woff2`;
      const target = join(OUT_DIR, file);

      const bytes = await getFontBytes(srcUrl);
      try {
        await writeFile(target, bytes, { flag: "wx" });
        downloaded += 1;
        console.log(`+ ${file} (${(bytes.length / 1024).toFixed(1)} KiB)`);
      } catch (error) {
        if (error.code !== "EEXIST") throw error;
        reused += 1;
      }

      declarations.push({ family, weight: weightLabel, style: group[0].style, file });
    }
  }

  
  const byFamily = new Map();
  for (const face of declarations) {
    const list = byFamily.get(face.family.slug) ?? [];
    list.push(face);
    byFamily.set(face.family.slug, list);
  }

  const lines = [
    "/*",
    " * Self-hosted dashboard fonts. GENERATED by scripts/fetch-fonts.mjs.",
    " *",
    " * Do not edit by hand: change the family list in the script and run",
    " * `npm run fonts`. The files live in src/web/public/fonts and are served by",
    " * the gateway, so the UI makes no outbound request to render text.",
    " */",
    "",
  ];

  for (const [, faces] of byFamily) {
    const display = faces[0].family.display;
    lines.push(`/* ${display} */`);
    for (const face of faces) {
      lines.push(
        "@font-face {",
        `  font-family: "${display}";`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        "  font-display: swap;",
        `  src: url("/fonts/${face.file}") format("woff2");`,
        "}",
        "",
      );
    }
  }

  await writeFile(CSS_OUT, lines.join("\n"));
  console.log(
    `\n${declarations.length} face(s) written to styles/fonts.css ` +
      `(${downloaded} downloaded, ${reused} already present)`,
  );
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
